ednp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from django.urls import path, include

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views
from django.views.generic.base import TemplateView

from wagtail.contrib.sitemaps.views import sitemap

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^ednps-admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    path('planfinder/', include('planfinder.urls')),
    path('lhn/', include('lhn.urls')),

    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    url('^sitemap\.xml$', sitemap),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lhn/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.LocalAuthorityLHNListView.as_view(), name='lhn'),
    path('la/<int:pk>', views.LocalAuthorityLHNDetailView.as_view(), name='lhn-detail'),
    path('county/<int:pk>', views.CountyDetailView.as_view(), name='county-detail'),
]

lhn/models.py
from django.db import models
from django.urls import reverse
from decimal import Decimal


# Create your models here.

class County(models.Model):
    name = models.CharField(max_length=99)

    class Meta:
        verbose_name = "County"
        verbose_name_plural = "Counties"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('county-detail', args=[str(self.id)])


class LocalAuthorityLHN(models.Model):
    la_code = models.CharField(max_length=99, default ="")
    la_area = models.CharField(max_length=99)
    county = models.ForeignKey(County, on_delete=models.CASCADE, blank=True, null=True)
    hp_2018 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2019 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2020 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2021 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2022 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2023 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2024 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2025 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2026 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2027 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2028 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2029 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2030 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2031 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2032 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2033 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2034 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2035 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2036 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2037 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2038 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    hp_2039 = models.DecimalField(max_digits=10, decimal_places=3, default=0, blank=True, null=True)
    med_aff_rat_2017 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    med_aff_rat_2018 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    med_aff_rat_2019 = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Local Authority area"
        verbose_name_plural = "Local Authority areas"
        ordering = ['la_area']

    def __str__ (self):
        return self.la_area

    def get_absolute_url(self):
        return reverse('lhn-detail', args=[str(self.id)])


    #### calc 2018 ####
    def projected_household_growth_2018(self):
        return Decimal((self.hp_2028 - self.hp_2018) * 1000)

    def adj_factor_2018(self):
        x = Decimal(self.med_aff_rat_2017)
        y = Decimal(4)
        z = Decimal(0.25)
        return (1 + (((x-y)/y)*z))

    def lhn_2018(self):
         x = Decimal(self.projected_household_growth_2018())
         y = Decimal(self.adj_factor_2018())
         return Decimal((x * y) / 10)

    #### calc 2019 ####
    def projected_household_growth_2019(self):
        return Decimal((self.hp_2029 - self.hp_2019) * 1000)

    def adj_factor_2019(self):
        x = Decimal(self.med_aff_rat_2018)
        y = Decimal(4)
        z = Decimal(0.25)
        return (1 + (((x-y)/y)*z))

    def lhn_2019(self):
         x = Decimal(self.projected_household_growth_2019())
         y = Decimal(self.adj_factor_2019())
         return Decimal((x * y) / 10)

    #### calc 2020 ####
    def projected_household_growth_2020(self):
        return Decimal((self.hp_2030 - self.hp_2020) * 1000)

    def adj_factor_2020(self):
        x = Decimal(self.med_aff_rat_2019)
        y = Decimal(4)
        z = Decimal(0.25)
        return (1 + (((x-y)/y)*z))

    def lhn_2020(self):
         x = Decimal(self.projected_household_growth_2020())
         y = Decimal(self.adj_factor_2020())
         return Decimal((x * y) / 10)

lhn/views.py
from django.shortcuts import render
from django.views import generic
from .models import LocalAuthorityLHN, County
# Create your views here.

class LocalAuthorityLHNListView(generic.ListView):
    model = LocalAuthorityLHN
    template_name = 'lhn/local_authority_lhn_list.html'

class LocalAuthorityLHNDetailView(generic.DetailView):
    model = LocalAuthorityLHN
    template_name = 'lhn/local_authority_lhn_detail.html'

class CountyDetailView(generic.DetailView):
    model = County
    template_name = 'lhn/county_detail.html'

ednp/templates/lhn/county_detail.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<!-- Page Content -->
<div class="container">
   <div class="row">
      <!-- Post Content Column -->
      <div class="col-sm-8">
         <!-- Title -->
         <h1 class="mt-4">Local Housing Need - LAs in {{ county.name }}</h1>
         </h1>
         <hr>
         <!-- Date/Time -->
         <p>Compare Local Housing Need figures for all local authority areas in {{ county.name }}.</p>
         <hr>
         <p>The table shows Local Housing Need figures for the current and previous years, for all
         local authority areas in {{ county.name }}. Local Housing Need has been calculated using the government's
         <a href="https://www.gov.uk/guidance/housing-and-economic-development-needs-assessments">standard method</a>. Note that no cap has been applied.<br /><br />
         Sort the table by clicking column headings.
         </p>
         <!-- Post Content -->
         <p class="lead">
            <h3>LHN for local authority areas in {{ county.name }}</h3>
         <table class="table table-hover sortable">
            <thead>
               <tr>
                  <th style="text-align:left">Local Authority</th>
                  <th style="text-align:center">Annual LHN 2018</th>
                  <th style="text-align:center">Annual LHN 2019</th>
                  <th style="text-align:center">Annual LHN 2020</th>
               </tr>
            </thead>
            <tbody id="myTableBody">
               {% for la in county.localauthoritylhn_set.all %}
               <tr>
                  <td style="text-align:left"><a href="{{ la.get_absolute_url }}">{{ la.la_area }}</a></td>
                  <td style="text-align:center">{{ la.lhn_2018 | floatformat:0 }}</td>
                  <td style="text-align:center">{{ la.lhn_2019 | floatformat:0 }}</td>
                  <td style="text-align:center">{{ la.lhn_2020 | floatformat:0 }}</td>
               </tr>
               {% endfor %}
            </tbody>
         </table>

         </p>
         <br /><br />
         <p style="text-align:right;"><a href="/lhn/">&larr; Back</a></p>
         <hr>
      </div>
      <!-- Sidebar Widgets Column -->
      <div class="col-sm-4">

      </div>
   </div>
</div>
<script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
{% endblock %}

ednp/templates/lhn/local_authority_lhn_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Page Content -->
<div class="container">
   <div class="row">
      <!-- Post Content Column -->
      <div class="col-sm-8">
         <!-- Title -->
         <h1 class="mt-4">{{ localauthoritylhn.la_area }}'s Local Housing Need</h1>
         </h1>
         <hr>
         <!-- Date/Time -->
         <p><strong>LA area: {{ localauthoritylhn.la_area }} | ONS area code: {{ localauthoritylhn.la_code }} | County: <a href="{{ localauthoritylhn.county.get_absolute_url }}">{{ localauthoritylhn.county }}</a></strong></p>
         <hr>
         <p>
             The data shows the Local Housing Need figure for {{ localauthoritylhn.la_area }} - for the current year
             and in previous years, <i>using the relevant data at that point in time.</i>
             The <strong>Household change (10 years)</strong> column calculates household growth over a 10 year period from the base year.
             The <strong>Adjustment factor</strong> has been calculated using the most recently available median affordability ratio figure - <i>at that time</i>.<br /><br />
             No cap has been applied to the Local Housing Need figures presented. Figures shown are rounded.<br /><br />
             Sort the table by clicking column headings.
         </p>


         <!-- Post Content -->
         <p class="lead">
            <h3>{{ localauthoritylhn.la_area }} LHN data</h3>
         <table class="table table-hover sortable">
            <thead>
               <tr>
                  <th>Year</th>
                  <th style="text-align:center">Household change<br />(10 yrs)</th>
                  <th style="text-align:center">Adjustment factor</th>
                  <th style="text-align:center">Annual Local Housing Need</th>
               </tr>
            </thead>
            <tbody id="myTableBody">
                <tr>
                  <td>2020</td>
                  <td style="text-align:center">{{ localauthoritylhn.projected_household_growth_2020 | floatformat:0 }}</td>
                  <td style="text-align:center">{{ localauthoritylhn.adj_factor_2020 | floatformat:3 }}</td>
                  <td style="text-align:center">{{ localauthoritylhn.lhn_2020 | floatformat:0 }}</td>
                </tr>
                <tr>
                  <td>2019</td>
                  <td style="text-align:center">{{ localauthoritylhn.projected_household_growth_2019 | floatformat:0 }}</td>
                  <td style="text-align:center">{{ localauthoritylhn.adj_factor_2019 | floatformat:3 }}</td>
                  <td style="text-align:center">{{ localauthoritylhn.lhn_2019 | floatformat:0 }}</td>
                </tr>

               <tr>
                  <td>2018</td>
                  <td style="text-align:center">{{ localauthoritylhn.projected_household_growth_2018 | floatformat:0 }}</td>
                  <td style="text-align:center">{{ localauthoritylhn.adj_factor_2018 | floatformat:3 }}</td>
                  <td style="text-align:center">{{ localauthoritylhn.lhn_2018 | floatformat:0 }}</td>
                </tr>

            </tbody>
         </table>

         </p>
         <br /><br />
         <p style="text-align:right;"><a href="/lhn/">&larr; Back</a></p>
         <hr>
      </div>
      <!-- Sidebar Widgets Column -->
      <div class="col-sm-4">

      </div>
   </div>
</div>
<script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
{% endblock %}

ednp/templates/lhn/local_authority_lhn_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% if localauthoritylhn_list %}
<!-- Page Content -->
<div class="container">
   <div class="row">
      <!-- Post Content Column -->
      <div class="col-sm-8">
         <!-- Title -->
         <h1 class="mt-4">Database of Local Housing Need</h1>
         </h1>
         <!-- Author -->
         <p class="lead">
            by
            <a href="/about">Ed Dade</a>
         </p>
         <hr>
         <!-- Date/Time -->
         <p>Local Housing Need data for local authority areas in England.</p>
         <hr>
         <p>
             Local Housing Need is the government's <a href="https://www.gov.uk/guidance/housing-and-economic-development-needs-assessments">standard method</a>
             for determining the number of new homes required to be built in each local planning authority area. The table below
             presents the annual Local Housing Need figure for each local authority area for the current year and previous years. <br /><br />
             LHN has been calculated using the ONS's 2014-based household projections. The local authorities listed represent
             those described in the household projections data. Note that some local authorities and their
             geographies have changed since publication.<br /><br />
             For some local authorities, the annual LHN figure may be capped depending on the extent of increase
             in the housing requirement. No cap has been applied in the data presented.
            <ul>
                 <li>Click a local authority name to view more info about how the LHN has been calculated for that area.</li>
                 <li>Click a 'county' to compare all local authorities in the county.</li>
                 <li>Sort the table by clicking headings.</li>
            </ul>
             </p>
             <br />
             <h3>Local Housing Need by local authority area</h3>
         <!-- Post Content -->
         <p class="lead">
         <table class="table table-hover sortable">
            <thead>
               <tr>
                  <th style="text-align:left">Local Authority</th>
                  <th style="text-align:left">County</th>
                  <th style="text-align:center">Annual LHN 2018</th>
                  <th style="text-align:center">Annual LHN 2019</th>
                  <th style="text-align:center">Annual LHN 2020</th>
               </tr>
            </thead>
            <tbody id="myTableBody">
               {% for la in localauthoritylhn_list %}
               <tr>
                  <td style="text-align:left"><a href="{{ la.get_absolute_url }}">{{ la.la_area }}</a></td>
                  <td style="text-align:left"><a href="{{ la.county.get_absolute_url }}">{{ la.county }}</a></td>
                  <td style="text-align:center">{{ la.lhn_2018 | floatformat:0 }}</td>
                  <td style="text-align:center">{{ la.lhn_2019 | floatformat:0 }}</td>
                  <td style="text-align:center">{{ la.lhn_2020 | floatformat:0 }}</td>
               </tr>
               {% endfor %}
            </tbody>
         </table>

         <br />
         <p>This data has been provided for information. It is advisable to contact the relevant
         local authority to confirm the area's housing requirement. For questions or feedback, please contact <a href="mailto:info@neighbourhood-planning.co.uk">info@neighbourhood-planning.co.uk</a>.</p>
         {% else %}
         <p>There are no local authorities in database.</p>
         {% endif %}
         </p>
         <br /><br />
         <p style="text-align:right;"><a href="/">&larr; Back</a></p>
         <hr>
      </div>
      <!-- Sidebar Widgets Column -->
      <div class="col-sm-4">

      </div>
   </div>
</div>
<script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
{% endblock %}